### ISSUE TITLE
Running in Nashorn

### ISSUE THREAD

**Issue by austinbruch** [medialize/sass.js#102]
I'm not sure if this is the right place for questions like this. If not, please direct me elsewhere.

I'm looking to run sass.js (or whatever variant is needed) in the JVM, and it sounds like Nashorn is the best suited engine to do so. However, the [documentation](https://github.com/medialize/sass.js/blob/master/docs/getting-started.md) is a little confusing regarding which distribution file to use when running in Nashorn.

Should I be using `sass.js`, or `sass.sync.js`? I've tried both, neither giving me the results I'm looking for.

Using `sass.js`, I'm able to load script into the engine, but I am unable to use the "synchronous" api i.e. `Sass.compile...`, and it seems like this version requires WebWorkers. Does this mean I also need to load in `sass.worker.js`?

Using `sass.sync.js`, while loading that script into the engine, I get the following error:
```
javax.script.ScriptException: TypeError: X is not a function in <eval> at line number 73
```
Obviously, this is not easily parsable given the state of the source file.

For reference, my Java code looks like this:

```
javax.script.ScriptEngine engine = new javax.scriptScriptEngineManager().getEngineByName("nashorn");
try {
	engine.eval("sass.js script here");
	...
} catch (Exception e) {
	throw new RuntimeException(e);
}
```

**Comment by rodneyrehm** [comment]
> Should I be using sass.js, or sass.sync.js? I've tried both, neither giving me the results I'm looking for.

* `sass.js` is what one would use in a browser (where you can run Workers). It contains the API, but not libsass (which is run in a Worker)
* `sass.sync.js` contains all of the API and libsass and is generally what one would use in any context that does not allow access to Workers. This is what *you* want to load into nashorn, this is also what we use in Node.

Unfortunately I don't know much about Nashorn, so cannot tell you why it's failing. I could point you at https://github.com/m4r71n/sass.js-rhino-nashorn/blob/master/src/TestNashorn.java (via [this comment](https://github.com/medialize/sass.js/issues/36#issuecomment-178819679)), but I have no idea if that helps…

**Comment by austinbruch** [comment]
Thanks for the link, somehow I missed that comment while reading that issue the other day. Using the same sass.js files as used in that sample (a nashorn shim and sass.sync.js from the cleanup-initialization branch), I was able to get sass.js to work. However, that version is quite old (~2016) and I'd like to be as up to date as I can. This is a good start, at least. I'll continue to investigate using the latest `sass.sync.js`.

**Comment by urzds** [comment]
Did you get this to work?

**Comment by austinbruch** [comment]
Unfortunately I had to put this on the shelf shortly after I closed this issue. I did not get to where I wanted but I don’t recall exactly how close I got. I will try to get back to you

**Comment by terjedahl** [comment]
Having just worked on [lein-sass](https://github.com/terjedahl/lein-sass) I found that the latest version of `sass.sync.js` to load in Nashorn without any problems is 0.10.8.  Currently, though, I believe lein-sass is using 0.9.13.
