### ISSUE TITLE
Unexpected token < in saas.worker.js

### ISSUE THREAD

**Issue by suryaprakash07** [medialize/sass.js#103]
I followed the instructions as said in [https://github.com/medialize/sass.js/blob/master/docs/getting-started.md].

I installed the saas.js using npm i saas.js and included the saas.js into scripts under angular.json.

When i use this starter code 
 var sass = new Sass();
  var scss = '$someVar: 123px; .some-selector { width: $someVar; }';
  sass.compile(scss, function(result) {
    console.log(result);
  });
I was getting **Unexpected token <** in saas.worker.js.
Please help me to fix this issue.

**Comment by rodneyrehm** [comment]
a) what does the DevTools network console say about loading `sass.worker.js`?
b) what browser did this happen with?
c) is there any more information about the error?

**Comment by suryaprakash07** [comment]
**Issue : ** 
As it was not able to locate the sass.worker.js it was directing to index.html and it took the **<**DOCTYPE HTML> ( < ) and it resulted back with unexpected token (<).

The error has been fixed by loading the sass.worker.js from my local directory.
**Solution : **
--------------------------------------------
**Sass.setWorkerUrl(assets/js/sass.worker.js)**
---------------------------------------------
 from my local directory instead of loading it from the **node_modules/sass.js/dist/sass.worker.js**.
This helped me to fix this problem.
