### ISSUE TITLE
Synchronous API broken

### ISSUE THREAD

**Issue by johnbrandle** [medialize/sass.js#104]
`
Sass.compile(value, function(result) 
{
	console.log('test2');
});
console.log('test1');`

outputs:

test1
test2

**Comment by rodneyrehm** [comment]
There is no *synchronous* execution of the compiler. synchronous refers to "being executed on the main event-loop" as [Using the Synchronous API](https://github.com/medialize/sass.js/blob/master/docs/getting-started.md#using-the-synchronous-api-in-the-browser) in the browser explains. Do we need to improve our docs?

**Comment by johnbrandle** [comment]
Is there a quick hack I could do to make it execute synchronously? I need this for non-production code.

**Comment by rodneyrehm** [comment]
Not that I'm aware of. I believe we had to go async when we added the [importer callback](https://github.com/medialize/sass.js/blob/master/docs/api.md#the-importer-callback), But I could be mistaken.
