### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by dharmatv** [medialize/sass.js#112]
my issue is same as [#103](https://github.com/medialize/sass.js/issues/103) but i had try to provide sass.working.sass file in local folder and nodemodules but output look likes 

Uncaught SyntaxError: Unexpected token <

**Comment by rodneyrehm** [comment]
did you see what the proble of #103 was?

**Comment by dharmatv** [comment]
yes i saw 

when i am compile sass code, error was show Uncaught SyntaxError: Unexpected token <  in console

i click on that error it was directing to index.html and it took the i.e first line and it resulted back with unexpected token (<).

var Sass = require('../../node_modules/sass.js/dist/sass.js');    // this is node_modules directory 
      Sass.setWorkerUrl('./sass.worker.js');  // this is local directory 
      var sass = new Sass();
      var testScss1 = '$testColour1: #ff0000' + '.box { color: $testColor1 }';
      sass.compile(testScss1, function(result) {
      console.log("compiled", result.text);
    });

in #103 problem is same but he did get solution by sass.worker.js file was given by locally but in my situation also provide same but i didn't get solution again same error was appear

**Comment by rodneyrehm** [comment]
As far as I understand sass.js is not properly loaded. a webserver responds with a 404 Not Found and some HTML and the browser fails to parse that as JS.

**Comment by dharmatv** [comment]
again i am given like 

 var Sass = require('sass.js/dist/sass.js');
      Sass.setWorkerUrl('sass.js/sass.worker.js');
      var sass = new Sass();
      var testScss1 = '$testColour1: #ff0000';
      sass.compile(testScss1, function(result) {
      console.log("compiled", result.text);
    });

**Comment by dharmatv** [comment]
at finally i got solution 

Thanks @rodneyrehm
