### ISSUE TITLE
"Invalid CSS after "...height: 340px;'": expected "{", was """

### ISSUE THREAD

**Issue by dharmatv** [medialize/sass.js#113]
i am compiling scss file to css 

var sassStyles="";   //https://demo7505738.mockable.io/sassStyles
(Note: string appear like above link)

sass.compile(sassStyles, function(result) {
      console.log("compiled", result);
    }); 

output will show error like
{
column: 19520
file: "stdin"
formatted: "Error: Invalid CSS after "...height: 340px;'": expected "{", was ""↵        on line 1 of /stdin↵>> ay-900;$pre-scrollable-max-height: 340px;'↵   ------------------------------------------^↵"
line: 1
message: "Invalid CSS after "...height: 340px;'": expected "{", was """
status: 1

}

**Comment by rodneyrehm** [comment]
The compiler is complaining about invalid input - why do you think this a problem of sass.js?

**Comment by dharmatv** [comment]
it means i am giving valid input string as input to that sass.js compiler

can you please check that link, i think that string format is perfect for input to sass.js

**Comment by rodneyrehm** [comment]
opening the content at https://demo7505738.mockable.io/sassStyles in VS Code already shows me the following problems:

![screenshot 2019-01-04 at 10 51 38](https://user-images.githubusercontent.com/186837/50682311-babc4d00-100e-11e9-8b56-8102881dbf2a.png)

running your SCSS through node-sass gives a similar response:

```
node-sass test.scss
{
  "status": 1,
  "file": "…/test.scss",
  "line": 1,
  "column": 8836,
  "message": "Invalid CSS after \"...eplace(url(data\": expected expression (e.g. 1px, bold), was \":image/svg+xml;$cus\"",
  "formatted": "Error: Invalid CSS after \"...eplace(url(data\": expected expression (e.g. 1px, bold), was \":image/svg+xml;$cus\"\n        on line 1 of test.scss\n>> x-indicator-icon-checked: str-replace(url(data:image/svg+xml;$custom-checkbo\n   ------------------------------------------^\n"
}
```

Please fix your input and try again.
