### ISSUE TITLE
how to set compile source base direction?

### ISSUE THREAD

**Issue by zfha** [medialize/sass.js#125]
My files structure is :

```
| -- index.html
     | -- style
           | -- nav.scss
           | -- index.scss
```

First,  I use `writeFile` add `nav.scss`.

```
sass.writeFile('style/nav.scss', 'xxx');
```

Then,  I compile `index.scss` source content.
```
sass.compile('@import './nav.scss', function(){})
```

but I  get this error:
```
Error: File to import not found or unreadable: ./nav.scss.
        on line 13:1 of /style
>> @import './nav.scss';
```

how to set the `compile source base directory`

**Comment by rodneyrehm** [comment]
> how to set the compile source base directory

 you can't. the working directory is fixed to "root".  I'd suggest to also `writeFile()´ your `style/index.scss` and  the use `sass.compileFIle('style/index.scss')`.
