### ISSUE TITLE
Running "shell:prepareLibsass" (shell) task fails: Fatal error: strderr is not defined

### ISSUE THREAD

**Issue by bassjobsen** [medialize/sass.js#30]
```
Running "shell:prepareLibsass" (shell) task
Preparing libsass version 3.2.2
  cleaning target directory
  downloading repository to target directory
Cloning into 'libsass'...
  checking out branch/tag and initializing submodules
Note: checking out '3.2.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 66631c0... Merge pull request #1156 from xzyfer/feat/salt-the-earth-of-compact

Running "get-emscripten-version" task
Fatal error: strderr is not defined
```

**Comment by rodneyrehm** [comment]
Since your output says `Running "get-emscripten-version" task`, I don't think it's `shell:prepareLibsass` that is failing. The task is trying to output `strderr` while it should be `stderr`. I fixed that in master just now. I assume you don't have emscripten installed / available in `PATH`.

**Comment by bassjobsen** [comment]
thanks. Indeed i have to install emscripten. For some reason i expected that running `npm install`  also installed it. I hope that building the latest version possible fixed #29

**Comment by bassjobsen** [comment]
Well now i can run ./emcc -v:

    ~/Dropbox/testomgeving/emscripten$ ./emcc -v
    WARNING  root: (Emscripten: settings file has changed, clearing cache)
    INFO     root: (Emscripten: Running sanity checks)
    emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.32.0
    clang version 3.6.0 (https://github.com/kripken/emscripten-fastcomp-clang ba2eba3c4548c27b82bf945e8eba37bf630585a8) (https://github.com/kripken/emscripten-fastcomp bdf2fc7e758ee9a4594bed666d0a7a86e6e787b1)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.2
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
    Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
    Candidate multilib: .;@m64
    Selected multilib: .;@m64
    INFO     root: (Emscripten: Running sanity checks)

And `./emscripten`:

# this helps projects using emscripten find it
    EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN') or       '/home/bass/Dropbox/testomgeving/emscripten') # directory

I still got the error mentioned above. Should i have to link `emcc` globally?

**Comment by rodneyrehm** [comment]
> Should i have to link emcc globally?

it needs to be available in PATH, yes.

I installed emscripten via homebrew, btw. `brew install emscripten --HEAD` (the --HEAD option requires compiling emscripten on your system, rather than downloading binaries - this can take a *while*).

**Comment by bassjobsen** [comment]
Well okay, adding emscripten to the path, solves this issue.

Notice that on ubuntu i can also run `sudo apt-get install emscripten` which installs version 1.10.0. Running `emcc --version` for  version 1.10.0. returns a first line with the commit nummer NOT set:
`emcc (Emscripten GCC-like replacement) 1.32.0 ()` which means that the `get-emscripten-version` task fails in the first place.

Also the dependency for the closure compiler was missing, see #31

**Comment by rodneyrehm** [comment]
> which means that the get-emscripten-version task fails in the first place.

fixed the regex accordingly…
