### ISSUE TITLE
Missing "ws" dependency (when in NodeJS)?

### ISSUE THREAD

**Issue by theefer** [medialize/sass.js#34]
The `sass.sync.js` file seems to require the `"ws"` package under certain conditions (when in NodeJS), but that package isn't in the list of dependencies of the `package.json`. Is that intentional?

This is preventing `sass.js` to be used in NodeJS from JSPM, which I need to do as part of my [Sass plugin for SystemJS](https://github.com/theefer/plugin-sass).

Thanks for this great project though, the plugin wouldn't be possible without it!

**Comment by rodneyrehm** [comment]
> The sass.sync.js file seems to require the "ws" package under certain conditions (when in NodeJS), but that package isn't in the list of dependencies of the package.json. Is that intentional?

I'm unaware of a package called "ws". If anything, it's a dependency introduced by emscripten. what are the "certain conditions"? I just installed sass.js 0.9.2 and ran a simple compile test - worked fine with node 0.10.33 and 0.12.6. What's the error say exactly?

> Thanks for this great project though, the plugin wouldn't be possible without it!

Why aren't you using the much faster [node-sass](https://github.com/sass/node-sass?

**Comment by theefer** [comment]
> What's the error say exactly?

```
err  Error: Error loading "npm:ws" at file:/home/seb/work/jspm-dev/test-sass-plugin/jspm_packages/npm/ws.js
     Error loading "npm:ws" from "github:theefer/plugin-sass@master/sass-builder" at file:/home/seb/work/jspm-dev/test-sass-plugin/jspm_packages/github/theefer/plugin-sass@master/sass-builder.js
     ENOENT, open '/home/seb/work/jspm-dev/test-sass-plugin/jspm_packages/npm/ws.js'
```

I can see references to `"ws"` in the sync file, although you are right that it's likely coming from emscripten. It seems to only get imported in a Node context, but I was able to run some code by doing a simple test in Node like you did, so not sure exactly when that's supposed to get invoked..

> Why aren't you using the much faster [node-sass](https://github.com/sass/node-sass)?

The plugin needs to be able to run and transpile on-the-fly dynamically in the browser, which is why I use sass.js.

JSPM also supports offline bundling, in which case the processing is done in NodeJS. In theory, it'd make more sense to use node-sass in that case, however there are [other issues](https://github.com/theefer/plugin-sass/issues/5) with that currently. Maybe I will dig into these further as that seems like a sensible path.

Thanks for the quick response!

**Comment by rodneyrehm** [comment]
emscripten loads ws in [library_sockfs](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/library_sockfs.js#L201). I'm not sure how you got there, though…

**Comment by theefer** [comment]
Ah, I think it's because of the way SystemJS parses this out as a static dependency by inspecting the (compiled) source tree, and it wants to guarantee the package has been installed in case we reach that code path (this is needed for when running in a browser, which can go around stat'ing files).

If sass.js is never meant to reach that part of the code, I should be able to fix this as a workaround in SystemJS by providing an override which declares a dependency of sass.js on ws, even though it will never actually get loaded.

I will close this issue as I'm not sure any fix belongs here really. Thanks for your help!

I guess it does raise the question of how much code is being compiled in with emscripten that isn't being used and could be trimmed by dead code elimination to make sass.js smaller...? Not one for this issue though.

**Comment by rodneyrehm** [comment]
> I guess it does raise the question of how much code is being compiled in with emscripten that isn't being used and could be trimmed by dead code elimination to make sass.js smaller...?

That's a question you'd have to take to [emscripten](https://github.com/kripken/emscripten/).
