### ISSUE TITLE
Sass.js prepends "/sass/" for absolute file paths in Node.js

### ISSUE THREAD

**Issue by matthew-dean** [medialize/sass.js#35]
As the subject line says, I'm using Sass.js in Node. (It's a more effective cross-platform solution for a node-webkit app.) However, when I use the "compileFile" function, it prepends "/sass/" to the file path (and throws an error saying that the file can't be found, of course). Any idea why this happens and how to prevent it?

**Comment by matthew-dean** [comment]
Note, when I use the "compile" function instead, I can of course pass in the initial file contents, but imports fail anyway, even with a correct inputPath set.

**Comment by rodneyrehm** [comment]
You still need to use `writeFile` to pass your data to sass.js - it does *not* access your real FS.

**Comment by matthew-dean** [comment]
Oh. Interesting. How would you register files for Sass.js if the files to be requested are unknown? A custom importer function?

**Comment by rodneyrehm** [comment]
> A custom importer function?

[certainly a possibility](https://github.com/medialize/sass.js#importer-callback-function):

```js
Sass.importer(function(request, done) {
  // find the correct path based on request
  FS.readFile(request.resolved, {encoding: 'utf8'}, function(err, data) {
    if (err) {
      done({
        error: String(err)
      });
    } else {
      done({
        content: data
      });
    }
  });
});
```

see [Importer._libsassPathVariations()](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L60-L81) for how `@import` is resolved by libsass.

**Comment by matthew-dean** [comment]
The importer works, thanks! :)

**Comment by rodneyrehm** [comment]
can you share what you're working on?

**Comment by matthew-dean** [comment]
Sure: https://github.com/Crunch/Crunch-2

Crunch 1.x was just a Less editor / compiler. (http://crunchapp.net/) Crunch 2 adds that workflow to a bunch more pre-processing languages.

**Comment by dharmatv** [comment]
i got the same problem but how can i use importer in my project and in that code how to compile file

can you explain briefly @rodneyrehm
