### ISSUE TITLE
upgrade to libsass 3.3.2 "Eleanor"

### ISSUE THREAD

**Issue by rodneyrehm** [medialize/sass.js#40]
The branch [libsass-3.2.2](https://github.com/medialize/sass.js/tree/libsass-3.3.2) contains fixes for the changed C-APIs necessary to upgrade to [libsass 3.2.2](https://github.com/sass/libsass/releases/tag/3.3.2). Unfortunately the asynchronous importer breaks in that branch. I have no idea why this is happening (yet). The usual method of debugging (running with assertions and adding things to the empterpreter whitelist) doesn't help.

**Comment by DarkPark** [comment]
+1
but let it be [v3.3.2](https://github.com/sass/libsass/releases/tag/3.3.2)

**Comment by rodneyrehm** [comment]
ha! seems to be a typo in the issue and the branch name. of course this was meant to mean 3.3.2 :D

**Comment by rodneyrehm** [comment]
I had hoped that the issue would as magically disappear as it appeared at some point. It hasn't. After upgrading to libsass 3.3.3 and emscripten 1.35.22 I'm still not closer to having a clue why `emscripten_sleep()` is killing the process. I've opened kripken/emscripten#4046, hoping Alon has an idea…

**Comment by rodneyrehm** [comment]
upgrade to libsass 3.3.3 is released in [0.9.5](https://github.com/medialize/sass.js/releases/tag/0.9.5)

**Comment by DarkPark** [comment]
:+1:
