### ISSUE TITLE
bad benchmark

### ISSUE THREAD

**Issue by DarkPark** [medialize/sass.js#41]
```bash
node bin/benchmark.js
```

gives

```
Error: Cannot find module '../dist/sass.min.js'
```

and there is really no such file
so I've corrected it to sass.js and got this:

```
sass.js: 
node-sass: 
Fastest is 
```

**Comment by rodneyrehm** [comment]
I wasn't aware this benchmark thingie still existed. you'd have to use sass.sync.js, though

**Comment by DarkPark** [comment]
ok
corrected require statement to sass.sync.js
output is the same

**Comment by rodneyrehm** [comment]
Fixed the simple benchmark thingie… thx for the pointer :)

```
➜  node bin/benchmark.js
sass.js x 13,352 ops/sec ±1.38% (79 runs sampled)
node-sass x 15,768 ops/sec ±1.64% (76 runs sampled)
Fastest is node-sass
```

**Comment by rodneyrehm** [comment]
uhm… those results can't be correct, right? that would mean the emscripted library is almost as fast as the native binding… huh?

**Comment by DarkPark** [comment]
That was the idea behind Emscripten LLVM-to-JavaScript compiler :)
Seems it's a very good compiler.

**Comment by rodneyrehm** [comment]
The benchmark was reading the file, but not converting it to string. What it was testing is the input error handling, instead of the compiler.

```
➜  node bin/benchmark.js
sass.js x 22.61 ops/sec ±37.39% (67 runs sampled)
node-sass x 183 ops/sec ±1.21% (81 runs sampled)
Fastest is node-sass
```

That makes node-sass about 9x faster than sass.js.

**Comment by DarkPark** [comment]
rather big difference
according to this [benchmark](https://www.solitr.com/blog/2014/01/css-preprocessor-benchmark/) pure js LESS implementation is only twice slower than libsass

**Comment by rodneyrehm** [comment]
These benchmarks don't compare. `bin/benchmark.js` is basically running the same C++ code once via the native binding, once via emscripten. LESS is a completely different code base.
