### ISSUE TITLE
Twitter bootstrap and live edit

### ISSUE THREAD

**Issue by prestarocket** [medialize/sass.js#44]
Hello,

is it possible to make a live edit page that compile twitter bootstrap scss ? (like lessjs can dot it)
thank you      !

**Comment by rodneyrehm** [comment]
> is it possible to make a live edit page that compile twitter bootstrap scss ?

I'm not sure I understand what it is that you want exactly.

A "live edit page" is very much possible, as [sass.js.org](http://sass.js.org/) shows. The playground was built by @varemenos. It's using the [ACE Editor](https://github.com/ajaxorg/ace) to provide a convenient UI.

**Comment by prestarocket** [comment]
something like this : http://bootstrap-live-customizer.com/.

**Comment by rodneyrehm** [comment]
Yes, I don't see why you shouldn't be able to build something like that. It looks like a specialized version of [sass.js.org](http://sass.js.org)… Good luck!

**Comment by prestarocket** [comment]
ok thx

**Comment by bobby-brennan** [comment]
I'm trying to do something similar, but am having trouble resolving `@import` statements.

Is is possible to resolve `@import` from URLs? Specifically say I have a file `localhost:3000/styles.scss` - can I `@import "styles.scss"`, or do I need to manually request the file (and any dependencies) and pass its contents to sass.js?  It looks like the playground mocks the entire filesystem in-browser.

**Comment by bobby-brennan** [comment]
Never mind - found `preloadFiles`.  This is super useful - thanks!
