### ISSUE TITLE
How to compile a file get with preloadFiles ?

### ISSUE THREAD

**Issue by prestarocket** [medialize/sass.js#45]
Hello,

i preload a file with preloadFiles method but i can find a way to compile files preloads.. could you help me ?

**Comment by rodneyrehm** [comment]
Running the following code in [sass.worker.html](https://github.com/medialize/sass.js/blob/master/sass.worker.html) works fine for me:

```js
// HTTP requests are made relative to worker
var base = '../scss/';
// equals 'http://medialize.github.io/sass.js/scss/'

// the directory files should be made available in
var directory = '';

// the files to load (relative to both base and directory)
var files = [
  'demo.scss',
  'example.scss',
  '_importable.scss',
  'deeper/_some.scss',
];

// register the files to be loaded when required
sass.preloadFiles(base, directory, files, function() {
  console.log('files loaded')
  // once registered, compile
  sass.compile('@import "demo";', function(result) {
    console.log("compiled", result.text);
  });
});
```

instead of 

```js
sass.compile('@import "demo";', function(result) {
  console.log("compiled", result.text);
});
```

you could also do 

```js
sass.compileFile('demo.scss', function(result) {
  console.log("compiled", result.text);
});
```

**Comment by prestarocket** [comment]
i have this following error msg : 
"File to import not found or unreadable: bootstrap Parent style sheet: stdin"

But the file is loaded...

**Comment by rodneyrehm** [comment]
are you by any chance running

```js
sass.preloadFiles(…);
sass.compile(…);
```

instead of

```js
sass.preloadFiles(…, function() {
  sass.compile(…);
});
```

sass.compile() does not block / wait until preloadFiles is finished - that's what the callback is for.

**Comment by prestarocket** [comment]
no, i run compile in callback...in my file i have import fct. 
I make a test with basic scss in my file : .some-selector { color:red; }
And now, i have this error msg : 
"Invalid CSS after "bootstrap.scss": expected "{", was """

thx for your help

**Comment by rodneyrehm** [comment]
what's your current code look like?

**Comment by prestarocket** [comment]
` var sass = new Sass();

  // HTTP requests are made relative to worker
  var base = '../../scss/';
  // equals 'http://medialize.github.io/sass.js/scss/'

  // the directory files should be made available in
  var directory = 'scss/';

  // the files to load (relative to both base and directory)
  var files = [
    'bootstrap.scss',
  ];

  // download the files immediately
  sass.preloadFiles(base, directory, files, function() { 

    sass.compile('bootstrap.scss', function(result) {
        console.log("compiled", result);
      });

  });`

**Comment by prestarocket** [comment]
i add the script before
  <script src="sassjs-master/dist/sass.js"></script>

**Comment by rodneyrehm** [comment]
you may want to look at [syntax highlighting code](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and use `js` as language identifier for your fenced code blocks in the future.

**Comment by prestarocket** [comment]
ok sorry, my code : 
```
var sass = new Sass();

  // HTTP requests are made relative to worker
  var base = '../../scss/';
  // equals 'http://medialize.github.io/sass.js/scss/'

  // the directory files should be made available in
  var directory = 'scss/';

  // the files to load (relative to both base and directory)
  var files = [
    'bootstrap.scss',
  ];

  // download the files immediately
  sass.preloadFiles(base, directory, files, function() { 

    sass.compile('bootstrap.scss', function(result) {
        console.log("compiled", result);
      });

  });
```

**Comment by rodneyrehm** [comment]
```js
sass.compile('bootstrap.scss', function(result) {
  console.log("compiled", result);
});
```

`sass.compile` takes a source string to compile. you're looking for `sass.compileFile` if you want to give it a file name:

```js
sass.compileFile('bootstrap.scss', function(result) {
  console.log("compiled", result);
});
```

**Comment by prestarocket** [comment]
so stupid..sorry
i have now this error Internal Error: File to read not found or unreadable but i can find the solution alone (some path pb..).
thanx a lot !!!

**Comment by Simpleqode** [comment]
Did you find the solution to the "File to read not found or unreadable" issue? I am facing the same.
