### ISSUE TITLE
Build error in sass.worker.js (0.9.7)

### ISSUE THREAD

**Issue by elsifaka** [medialize/sass.js#47]
In Firefox 44.0.2, I do have:
    
    SyntaxError: missing ] in index expression -- sass.worker.js :14:60

In Google Chrome Version 48.0.2564.109 (64-bit)
I do have:

    Uncaught SyntaxError: Unexpected token ; -- sass.worker :14

When I switch to version 0.9.6 everything works.

Thank you

**Comment by rodneyrehm** [comment]
Interesting. I cannot confirm your finding. 

* Is your test online somwhere so I could have a look?
* Is it possible some browser plugin / firewall / proxy is interfering?
* Have you tried running the scripts in private mode in Chrome and Firefox?

**Comment by elsifaka** [comment]
I do use https://github.com/mobilexag/plugin-sass, I may have to open an issue there then.

Anyway, here are the test files to reproduce the issue. Please just change the `sass.js` version in `config.js`
[sassjs_jspm.zip](https://github.com/medialize/sass.js/files/134408/sassjs_jspm.zip)

**Comment by rodneyrehm** [comment]
> I do use https://github.com/mobilexag/plugin-sass, I may have to open an issue there then.

yes. please re-open this issue should the problem lie with sass.js.
