### ISSUE TITLE
Synchronous API isn't synchronous 

### ISSUE THREAD

**Issue by sedwards2009** [medialize/sass.js#48]
I would love to have a way of using sass.js which is truly synchronous, i.e. calling compile() should immediately compile the code and return the result, blocking the caller. The current Synchronous API isn't synchronous, instead it just runs on the main thread in an async fashion.

This is in the context of an Electron apps where I often don't want async behaviour and I don't want to have the headache of native modules with cross platform issues. (node-sass isn't supported running in Electron.)

**Comment by rodneyrehm** [comment]
It is not possible to provide a synchronous interface for something that is potentially asynchronous. As soon as you use an [Importer callback](https://github.com/medialize/sass.js/#importer-callback-function) that does not run synchronously, you're done.

I'm sorry, but a *truly synchronous* API is not possible at this time. Is there another way we could try easing your pain?

And yes, "Synchronous API" is misleading, it should be "Main Thread API".

**Comment by sedwards2009** [comment]
Thanks for the quick reply.

I understand why async is the default behaviour and often necessary. (i.e. IO in browsers etc).

Would it be possible to have a synchronous API with the perfectly reasonable limitation that all callbacks, custom functions etc are also synchronous? (Isn't libsass just plain synchronous C++ code anyway?)

**Comment by sedwards2009** [comment]
Changing the name is a very good idea too. I was a bit confused until I figured out what was going on.

**Comment by rodneyrehm** [comment]
> Would it be possible to have a synchronous API with the perfectly reasonable limitation that all callbacks, custom functions etc are also synchronous?

* That would mean that we'd have different function signatures for a/synchronous, which I'd very much like to avoid.
* As we're not able to inspect callback functions at registration, we wouldn't be able to provide adequate error messages.
* The same problem would come up with sass functions, should we ever get around to implementing them.

For simplicity's sake, I'd like to avoid any of that. I don't see the benefit…

> Isn't libsass just plain synchronous C++ code anyway?

Yes, but emscripten allows us to temporarily halt the execution to perform asynchronous operations.
