### ISSUE TITLE
Source Maps Cause Error

### ISSUE THREAD

**Issue by rafegoldberg** [medialize/sass.js#54]
Have been testing out `scss.js` and so far I _love_ it; way better than the [PHP compilers](https://github.com/leafo/scssphp/) I've toyed with! That said, I keep getting the following error whenever I try to compile `.scss` files with any `@import` statements (project config deets below):

```js
{ status:    3,
  message:   "map::at:  key not found",
  formatted: "Internal Error: map::at:  key not found↵", }
```

Haven't been able to debug of my own accord so any solutions/suggestions/pointers/tips/etc. would be much appreciated!

#### Files

The project architecture looks something like this:

```yaml
web/               #=SERVER ROOT
├ index.php        # script runs from here
├ lib/             #=BOWER COMPONENTS
│ ├─ sass.js/      # sass.js installed here
└ styles/          #=SASS BASE
    ├ test.scss    # main SCSS stylesheet
    └ _import.scss # @imported SCSS partial
```

> **Note:**
I'm using Grunt to spool a local PHP server. The above tree has been condensed for clarity; it _only_ shows the server's root directory, rather than the entire top-level Grunt project directory. (There are a few other PHP files on the server, as well as some Grunt config files in the top directory.)

#### Javascript

My `scss.js` configuration looks like this:

```js
$(document).ready(function(){

Sass.setWorkerUrl('lib/sass.js/dist/sass.worker.js');
sass = new Sass();

sass.importer(function(request, done) {
  // understand the concept but unsure what
  // I should do with this method, or if it
  // might help solve the source maps error
  console.log(request);
  done();
});

sass.preloadFiles(
  '../../../styles/', // root sass dir
  '', // directory
  ["_import.scss", "test.scss"],
  function(){
    sass.listFiles(function(list){console.log(list)});
    sass.compileFile('test.scss',function(result){console.log(result)});
  }
);

});
```

There're also some other JS scripts that're included beforehand:

```html
<script src="http://localhost:35729/livereload.js"></script> <!-- local livereload script -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> <!-- jquery, duh -->
<script src="lib/sass.js/dist/sass.js"></script> <!-- sass.js, wahoo! -->
```

#### SCSS Structure

Since this is a test implementation, my `.scss` files are extremely simple:

```scss
//=file: styles/test.scss
@import "import"
```

```scss
//=file: styles/_import.scss
.test {
  $var: 123px;
  content: $var;
}
```

#### Miscellaneous

Some other potentially pertinent details:

- **Operating System:** Mac OS X (10.11.3)
- **Server:** local server on `127.0.0.1:500` (via [`grunt-php`](https://github.com/sindresorhus/grunt-php) with livereload)

**Comment by rodneyrehm** [comment]
You seem to be running grunt and should therefore be able to run [grunt-sass](https://www.npmjs.com/package/grunt-sass) or [node-sass](https://www.npmjs.com/package/node-sass). Either option is far superior to anything sass.js can do.

* If you preload all your files, you don't need to register an importer callback.
* What do you intend to do with the generated Source Map file? Why is it configured to be written to directory `styles`, while the `test.scss` is loaded from root? Unless you use the inline Source Map option, you're not getting the SM processed by your browser.

**Comment by rafegoldberg** [comment]
Quickly: if you look at the Javascript code above you'll see I'm logging some details at various points; will paste here on the offchance they might provide some/any insight in to the issue:

- the **`list`** variable from the `sass.listFiles` method:
  
  ```javascript
  ["_import.scss", "test.scss"]
  ```
- the **`request`** variable from the `sass.importer` method:
  
  ```javascript
  { current: "import",
    previous: "/sass/test.scss",
    resolved: "/sass/import",
    path: "/sass/_import.scss",
    options: null }
  ```

**Comment by rafegoldberg** [comment]
@rodneyrehm why not `grunt-sass`, you ask? Well I'd absolutely _love_ to develop locally with Grunt, but my company prefers to do everything on their servers for various reasons... Alas. And as for those sourcemap options, that was just me fiddling around to see if I could resolve the error; meant to remove 'em before I posted this issue... 

But more to the point: 

> If you preload all your files, you don't need to register an importer callback.

So umm, yeah... that works perfectly. What an obvious solution; hitting myself for not trying that earlier! Anyway, thanks again for helping me out my man; I really appreciate it.

**Comment by rodneyrehm** [comment]
> but my company prefers to do everything on their servers for various reasons.

But that's not what is happening with sass.js, is it? Sass.js is executed in your user's browser, not your company's server. Unless you absolutely need to compile SCSS in the browser, *don't do it*.

**Comment by rafegoldberg** [comment]
Oh never in a million years would I do that! We only plan on using this in development on our staging servers.
