### ISSUE TITLE
Sass.preloadFiles() Inconsistency

### ISSUE THREAD

**Issue by rafegoldberg** [medialize/sass.js#55]
Hey, I've been having some difficulty getting the `Sass.preloadFiles()` method to consistently load the most recent contents of my SCSS partials. On initial compile this works as expected. But, when I make some changes to my partials and then try to **re**compile it doesn't always pull in the most recent changes. Sometimes it correctly loads in the updated files, but the other half of the time it doesn't and I have to reload the page to get it to pull in the changes. 

I'm not sure if I'm using it incorrectly (maybe I only have to run `preloadFiles` once, and it'll just magically pull in changes?) or if I should be using a different method (such as `lazyFiles`?) or what! All I know is I want to consistently pull in the most recent files without refreshing the page.

Lemme know re: any tips or if ya have a question about my setup. Any/all help is much appreciated in advance!

**Comment by rodneyrehm** [comment]
I don't see why the `.preloadFiles()` [handler](https://github.com/medialize/sass.js/blob/master/src/sass.api.js#L264-L281) should fail your use case. Is it possible the browser cache is interfering?

**Comment by rafegoldberg** [comment]
yes, that does seem most likely. next q isn't quite on topic, but would appreciate tips if you know of any good/quick ways to _“bust”_ the cache, so to speak? Something like, I know in certain scenarios you can append a random param to the end of the URL. (Hmmm, maybe that could work with the `.compileFile()` handler... #willtry)

**Comment by rodneyrehm** [comment]
@rafegoldberg does this problem still exist?

**Comment by rafegoldberg** [comment]
@rodneyrehm whoops, forgot to close. was a caching issue as you'd guessed. thanks for the tip.
