### ISSUE TITLE
Any way to call Sass.compile synchronously?

### ISSUE THREAD

**Issue by ericmuyser** [medialize/sass.js#56]
I want to be able to compile Sass synchronously like this:
`var styles = Sass.compile(rawStyles)`

Is there any way?

The reason is because I'm using this in React.js and if styles are set in a callback, it will delay rendering my component, which causes a content flash.

Currently using it in a callback like this (this runs in Node.js and browser but perhaps I could cut the browser support)
![image](https://cloud.githubusercontent.com/assets/156768/16179796/cbd9f634-3625-11e6-9e69-af71e58f358d.png)

Thanks in advance!

**Comment by rodneyrehm** [comment]
I'm afraid it is not possible to run the compiler synchronously. If you're able to run run this only in node, then use [node-sass](https://www.npmjs.com/package/node-sass).
