### ISSUE TITLE
Is there a way to create different importer for individual tasks with Node.js?

### ISSUE THREAD

**Issue by SCLeoX** [medialize/sass.js#57]
I am using Node.js V6.2.2 to create a building environment. I personally hate to install node-gyp stuff so I chose this library instead of node-sass.

The problem is, my building environment starts multiple tasks at same time. Different tasks need different importers.

I tried like this:

``` javascript
const sass = require('sass.js');
sass.importer(importer1);
sass.compile(text1, options1, callback1);
sass.importer(importer2);
sass.compile(text2, options2, callback2);
```

The tasks do piles up but **both task uses importer2**.

I also tried like this:

``` javascript
const Sass = require('sass.js');
sass1 = new Sass();
sass1.importer(importer1);
sass1.compile(text1, options1, callback1);
sass2 = new Sass();
sass2.importer(importer2);
sass2.compile(text2, options2, callback2);
```

And it worked but the importer is never get called so I get a lot of "file not exist" errors. I am pretty sure the importers are not get called in this case since I tried to put `function() {console.info(123);}` as importer but nothing appears on my computer;

I also tried this:

``` javascript
const sass = require('sass.js');
sass.compile(text1, {
  importer: importer1
}, callback1);
sass.compile(text2, {
  importer: importer2
}, callback2);
```

But, same. The importers never get called.

And here is my fourth try:

``` javascript
const _ = require('lodash');
const sassOrigin = require('sass.js');
sass1 = _.cloneDeep(sassOrigin);
sass1.importer(importer1);
sass1.compile(text1, options1, callback1);
sass2 = _.cloneDeep(sassOrigin);
sass2.importer(importer2);
sass2.compile(text2, options2, callback2);
```

But it is not working. XD For some reason, it never finishs cloning.

Anyways, I am getting crazy due to this problem. I personally think, the third way should work but it does not. I guess it is a bug or something. XD (<-- Actually I am not laughing but put a laughing face here may make readers happier XD)

**Comment by SCLeoX** [comment]
I just find a super stupid way to work around.

```javascript
sass1 = require('sass.js')
sass1.importer(importer1);
sass1.importer(importer1);
sass1.compile(text1, options1, callback1);
delete require.cache[require.resolve('sass.js')];
sass2 = require('sass.js')
sass2.importer(importer2);
sass2.compile(text2, options2, callback2);
```

And it works. But still, I do not think it is a proper way to solve this problem. Anyways, I am a genius. XD

**Comment by rodneyrehm** [comment]
Not liking node-gyp is a pretty weak reason to ditch node-sass for Sass.js. The performance penalty you're paying is *considerable*. node-sass is much more capable (in respect to extending Sass from JS) than Sass.js is at the moment (and forseeable future).

Sass.js is designed to run in WebWorkers. Node does not provide an API like that. If you want to run Sass.js in Node, you'll have to live with the fact that you can only run one instance at a time. The reason is that the communication between the emscripted C++ and your JS callbacks only works through shared state - and those are quite hard to manage to allow concurrency.

**Comment by SCLeoX** [comment]
>.> I use this just in building environment which means I do not really need to worry about the performance. Also, Sass.js is actually very fast. It takes about 3 seconds to compile whole materialize on my computer. Node-sass takes about 1 second. It is not too bad. :) (And here is something you might want to ignore: Installing VisualStudio may takes up to 6 hours which I can run 10800 times with sass.js XD)

Another thing you mentioned is shared state. I think there should be a way to somehow wrap the whole thing. As I mentioned in my last comment, there is a stupid way to solve this by deleting old cached require files. I think, there should be another better way.

At last, I believe, it must be a bug that `importer` passed with `options` not work. >.>

Anyways, my problem is solved. ヽ(✿ﾟ▽ﾟ)ノヽ(✿ﾟ▽ﾟ)ノヽ(✿ﾟ▽ﾟ)ノヽ(✿ﾟ▽ﾟ)ノ

**Comment by rodneyrehm** [comment]
closing because issue seems to be solved.

**Comment by SCLeoX** [comment]
No, it is not solved QAQ

My problem is solved but I solved it by working around XD.

If you put a importer in options and pass into sass.compile method it is not working. >.>
