### ISSUE TITLE
Sass.js does not allow nested @import

### ISSUE THREAD

**Issue by nelisbijl** [medialize/sass.js#58]
Nested imports as described here: 
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested-import

produce an error like:

err  Error: Invalid CSS after '...import "./test"': expected "{", was ";"
        on line 5 of stdin
&gt;&gt;     @import "./test";
   --------------------^

**Comment by rodneyrehm** [comment]
Sass.js is a transpiled version of [libsass](https://github.com/sass/libsass) and does not modify the parser/compiler in any way. Please file your issue with [libsass](https://github.com/sass/libsass).
