### ISSUE TITLE
Call sass.compile in angularjs controller?

### ISSUE THREAD

**Issue by seanmavley** [medialize/sass.js#60]
I wanted to do something like this:

```
  .controller('homeController', ['$scope', function($scope){
    var scss = '$someVar: 123px; .some-selector { width: $someVar; }';
    $scope.doCompile = function() {
        sass.compile(scss, function(result) {
        console.log(result);
      })
    }
  }])
```
If I wish to call the sass.compile function within an angularjs controller, how can i?

Sass.js installed and script added to index file

**Comment by rodneyrehm** [comment]
I have no idea how Angular works and what your problem with Angular is.

**Comment by CodyMorris** [comment]
@seanmavley ever get this working?

**Comment by seanmavley** [comment]
@CodyMorris Naa. Didn't bother to continue using it, rather switched to node-sass for building [my app](http://materialize.khophi.co). Depending on your use case, this might work for you, as is, however an integration with AngularJS or something similar would have made it even better, I think.
