### ISSUE TITLE
Webpack & Sass.js

### ISSUE THREAD

**Issue by jeremyrambo** [medialize/sass.js#64]
Has there been any thought about creating a [webpack](https://github.com/webpack) Sass loader based on this node project instead of the C-based [node-sass](https://github.com/sass/node-sass) effort?

**Comment by rodneyrehm** [comment]
Not on my part. If you're looking to create a webpack loader, maybe [simple-sass](https://www.npmjs.com/package/simple-sass) and [grunt-contrib-sassjs](https://github.com/amiramw/grunt-contrib-sassjs) can serve with ideas…

**Comment by NickHeiner** [comment]
I have built such a thing! https://www.npmjs.com/package/sassjs-loader

**Comment by rodneyrehm** [comment]
@NickHeiner nice! What's the benefit of making sass.js a devDependency?

**Comment by rodneyrehm** [comment]
closed by #76

**Comment by NickHeiner** [comment]
The convention for webpack loaders is to make the thing being wrapped a dev dependency. The idea is that this gives the user more control.
