### ISSUE TITLE
Custom importer: request.resolved returns different values on win32 and posix

### ISSUE THREAD

**Issue by NickHeiner** [medialize/sass.js#69]
Here's a demo script, using `sass.js@0.9.13`:

```js
var sassJs = require('sass.js'),
    path = require('path');

sassJs.importer(function(request, done) {
    console.log(request);
    done();
});

sassJs.compile(
    '@import "posix"', 
    {
        inputPath: path.posix.join('nested', 'directory', 'file.scss')
    }, function() {});

sassJs.compile(
    '@import "win32"', 
    {
        inputPath: path.win32.join('nested', 'directory', 'file.scss')
    }, function() {});
```

I would expect that `request.resolved` is the same when using both `path.posix` and `path.win32` to create the file path. However, this is not the case:

```
$ node sassjs-demo.js 
{ current: 'posix',
  previous: 'nested/directory/file.scss',
  resolved: '/nested/directory/posix',
  path: null,
  options: null }
{ current: 'win32',
  previous: 'nested\\directory\\file.scss',
  resolved: '/win32',
  path: null,
  options: null }
```

As you can see, `request.resolved` for win32 is `/win32`, when I would expect it to be `nested\\directory\\win32`. 

I don't know if this is a problem with sass.js or an upstream dependency, but I thought I'd start here and work my way up as needed. 😄

**Comment by rodneyrehm** [comment]
I'm currently at a conference, but wanted to provide a pointer anyway: [sass.importer.js](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L17). Note that this is [emscripten's PATH](https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html), not Node's.

**Comment by NickHeiner** [comment]
Thanks for sending the ping!

It does look like emcripten's PATH is problematic. Here's more behavior that surprises me. (I'm happy to open a separate issue for this if that'd be easier for you organizationally. I'm also happy to open an issue upstream with emscripten.)

```js
var sassJs = require('sass.js'),
    path = require('path');

console.log(
    'posix path variations', 
    sassJs.getPathVariations(path.posix.join('path', 'to', 'file'))
);

console.log(
    'win32 path variations', 
    sassJs.getPathVariations(path.win32.join('path', 'to', 'file'))
);
```

This produces:

```
$  node sassjs-demo.js 
posix path variations [ 'path/to/file',
  'path/to/_file',
  'path/to/_file.scss',
  'path/to/_file.sass',
  'path/to/_file.css',
  'path/to/file.scss',
  'path/to/file.sass',
  'path/to/file.css' ]
win32 path variations [ 'path\\to\\file',
  '_path\\to\\file',
  '_path\\to\\file.scss',
  '_path\\to\\file.sass',
  '_path\\to\\file.css',
  'path\\to\\file.scss',
  'path\\to\\file.sass',
  'path\\to\\file.css' ]
```

The `_` is prepended to the entire path for `win32`, instead of just the file name.

For now, I can work around these issues, but I wanted you to be aware :smile:.

**Comment by rodneyrehm** [comment]
As far as I can see emscripten's [path implementation](https://github.com/kripken/emscripten/blob/master/src/library_path.js) does not concern itself with windows paths (i.e. `\` as separator and drive-letter as root).

I have a hard time finding any examples using windows path notation within `@import` statements. Using `path/to/file.sass` instead of `path\to\file.sass` should work everywhere. I'd therefore suggest going with that.

**Comment by NickHeiner** [comment]
I'm surprised that emscripten doesn't handle Windows paths. Does it not have any notion of platform-specificity? 

I'm not running into this because I have SCSS like `@import 'path\to\file.scss';`. I'm building a Webpack plugin. The user will do something like:

**`C:\dev\workspace\main.scss`**
```scss
@import 'variables';
```

When I have a custom importer, which is necessary for the Webpack plugin to work, I get the following:

```js
sassJs.importer(function(request, done) {
    console.log(request);
    // ...
});
```

**`console output`**
```json
{
    "previous": "C:\\dev\\workspace\\main.scss",
    "resolved": "/variables",
    "path": null,
    "options: null
}
```

So, the user has not used Windows paths in `@import` statements, but `request.resolve` contains a surprising result.

**Comment by rodneyrehm** [comment]
> Does it not have any notion of platform-specificity?

apparently not. To make things worse, neither do I.

As far as I know Node's FS will treat `C:\foo\bar.txt` and `C:/foo/bar.txt` the same. Maybe your can try rewriting `\` to `/` before blowing it through [Sass.getPathVariation()](https://github.com/medialize/sass.js#resolving-file-names) from within the importer callback? If that works and generally rewriting the `\` to `/` does not cause any other problems, we may consider doing that in the [importer handler itself](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L17).

---

Also I'd like to point you towards [Dart Sass](http://blog.sass-lang.com/posts/1022316-announcing-dart-sass), which is likely going to render Sass.js obsolete at some point "soon", as development on libsass seems to have slowed to a crawl.

**Comment by rodneyrehm** [comment]
@NickHeiner are you still interested in solving this problem?

**Comment by NickHeiner** [comment]
Dart Sass is interesting! I didn't know about it. Thanks for pointing it out.

I was able to work around this problem in my code, so I don't have time to fix it upstream. 😦
