### ISSUE TITLE
Compile a  scss file wrong

### ISSUE THREAD

**Issue by jintangWang** [medialize/sass.js#70]
I had add `sass.js` and `sass.worker.js` in my project,here is my code:
``` js
var sass = new Sass();
var base = '../../furnace/';
var directory = '';
var files = [
	'audio/sass/audio.scss'
];
sass.preloadFiles(base, directory, files, function() {
	sass.listFiles(function callback(list) {
		console.log(list);
		sass.readFile(list[0], function callback(content) {
			if(content){
				sass.compile(content, function(result) {
					console.log(result);
				});
			}
		});
	});
});
```
I got the content of 'audio/sass/audio.scss',but because the first line is `@import "../../sass/_base";`,there is a wrong look like:

*File to import not found or unreadable: sass/_base↵Parent style sheet: stdin*

How do i fix it?thanks for your response

**Comment by rodneyrehm** [comment]
see [working with files](https://github.com/medialize/sass.js#working-with-files)

**Comment by jintangWang** [comment]
yeah,I know what you mean,but i use `compile()` in `readFile()`'s callback.And i have tested `compileFile()` looks like:
``` js
        sass.preloadFiles(base, directory, files, function() {
			sass.listFiles(function callback(list) {
				console.log(list);
				sass.compileFile(list[0],function(result){
					console.log(result);
				})
			});
		});
```
then i get the same wrong message.I think the first line of 'audio/sass/audio.scss' caused the problem.Here is it:
``` scss
@import "../../sass/_base";
```
Can you give me some advise?

**Comment by jintangWang** [comment]
My god,I found the solution.Here is my code:
``` js
        var base = '../../furnace/';
		var directory = '';
		var files = [
			'audio/sass/audio.scss',
			'sass/_base.scss'
		];
		sass.preloadFiles(base, directory, files, function() {
			sass.compileFile('audio/sass/audio.scss',function(result) {
				console.log(result.text);
			});
		});
```
As i said above,first line of 'audio/sass/audio.scss' is:
``` sass
@import "../../sass/_base";
```
I need preload ‘_base.scss’ before `@import` it.Thanks a lot.
