### ISSUE TITLE
compressed style doesn't produce correct source map

### ISSUE THREAD

**Issue by sormy** [medialize/sass.js#71]
"compressed" style doesn't produce correct source map
example: font-awesome sass
PS: clean-css works well

**Comment by rodneyrehm** [comment]
> "compressed" style doesn't produce correct source map

does it work properly in [node-sass](https://npmjs.org/package/node-sass)? Is there a reduced test case I could look at?

**Comment by rodneyrehm** [comment]
closing since there's been no response in 4 weeks.
