### ISSUE TITLE
Uncaught ReferenceError: sass is not defined

### ISSUE THREAD

**Issue by mikethedj4** [medialize/sass.js#83]
https://codepen.io/mikethedj4/pen/EXBjwd?editors=1010

I'm not sure what I'm doing wrong here. I'm following the [instructions on sass.js.org](https://github.com/medialize/sass.js/blob/master/docs/getting-started.md) and I keep getting....

> Uncaught ReferenceError: sass is not defined

Here's my Javascript:  
Can someone explain what I'm doing wrong and how I can get this to run?  

    var code = document.getElementById('code'),
        sass = new Sass('https://sass.js.org/js/sass.js/sass.worker.js'),
        scss = "$someVar: 123px; .some-selector { width: $someVar; }";

    sass.compile(scss, function(result) {
      code.value = result;
      console.log(result);
    });

**Comment by rodneyrehm** [comment]
I'm getting `Uncaught ReferenceError: Sass is not defined`, probably due to the fact that https://sass.js.org/js/sass.js/sass.js is not served with a valid certificate. Maybe try https://cdnjs.com/libraries/sass.js :)
