### ISSUE TITLE
sass.node.js fails to import files in Windows

### ISSUE THREAD

**Issue by rtruong** [medialize/sass.js#86]
When using [sass.node.js](https://github.com/medialize/sass.js/blob/0.10.5/dist/sass.node.js), it fails to import files in Windows.  Patching [importerCallback()](https://github.com/medialize/sass.js/blob/0.10.5/dist/sass.node.js#L37) as follows fixes the issue:

```
function importerCallback(request, done) {
  // sass.js works in the "/sass/" directory, make that relative to CWD
  var requestedPath = path.normalize(
    path.join(
      path.dirname(request.previous.replace(/^\/sass\//, '')),
      request.current
    )
  ).replace(/\\/g, '/');
  importFileToSass(requestedPath, done);
}
```

Using [0.10.5](https://github.com/medialize/sass.js/releases/tag/0.10.5).

**Comment by rtruong** [comment]
The problem seems to be that `request.resolved` is incorrect, possibly due to issues with differences in file system separators.

**Comment by rodneyrehm** [comment]
Thank you! Did you see #69? Would you like to send that as a PR?

**Comment by rtruong** [comment]
@rodneyrehm Please see https://github.com/medialize/sass.js/pull/87
