### ISSUE TITLE
What is the correct way to compile files in a tree?

### ISSUE THREAD

**Issue by ShayanJavadi** [medialize/sass.js#89]
I need to fetch a few folders with .scss files in them and compile them into css to send it to our backend. I came across sass.js which seems perfect for what I'm doing.

I've been messing with this library for a couple of hours now, and I can't seem to get it to work so I'm asking for help here.

here's a simple example of what I tried.

```
import sass from 'sass.js';

const baseUrl = getBaseUrl();
const scssfile = `${baseUrl}/public/scss/styles/someFile.scss`;

sass.compileFile(scssfile, (result) =>{
  console.log(result);
});
```

this and every other thing I tried returns an error. this one in particular returns undefined. Any help with the correct way to compile these files would be greatly appreciated.

**Comment by rodneyrehm** [comment]
Unless you [preload](https://github.com/medialize/sass.js/blob/master/docs/api.md#preloading-files) those files, you'll have to download them yourself. The [Importer Callback](https://github.com/medialize/sass.js/blob/master/docs/api.md#the-importer-callback) may be of interest to you.
