### ISSUE TITLE
input[type=url] { ... } fails to parse

### ISSUE THREAD

**Issue by ritwickdey** [medialize/sass.js#91]
Hi, I am facing a issue on parsing `input[type=url] {....}`.

**Input** 
```
input[type=url] {
  //todo
}
```
**Expected Output**
```
input[type=url] {
  //todo
}
```

**Actual Result**
```
Error: Invalid CSS after "i": expected 1 selector or at-rule, was "input[type=url] {"
        on line 1 of sass/c:\Users\ritwick\Desktop\New folder\New folder\test3.scss
>> input[type=url] {
   ^

```
![image](https://user-images.githubusercontent.com/18099464/28843753-f437280e-771f-11e7-8b23-746d3a861d15.png)

_NOTE: Even If I use `input[type=urlXYZ]`, there is also same error but if I use  `input[type="url"]` then no error._

[I am using this JS library to my VsCode Extension ([Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass)).]

I found that same issue is mentioned in here : https://github.com/sass/libsass/issues/2429

**Comment by rodneyrehm** [comment]
As you've already observed this issue originates in libsass, not sass.js. There's nothing sass.js can do until the next release of libsass fixed that bug. 

If you're looking for a workaround, this seems to work fine:

```scss
input[type="url"] {
  width: 123px;
}
```
