### ISSUE TITLE
Upgrade to libsass v3.5.x

### ISSUE THREAD

**Issue by djanosik** [medialize/sass.js#92]
Can you upgrade to libsass v3.5.x? Right now Sass.js uses a different version than the node-sass library.

**Comment by djanosik** [comment]
Now I see that 3.4.5 is the latest stable version of libsass. My bad, sorry.

**Comment by rodneyrehm** [comment]
we will upgrade to 3.5.x once there's a stable release. latest beta is [3.5.0.beta.3](https://github.com/sass/libsass/releases/tag/3.5.0.beta.3) vs stable [3.4.9](https://github.com/sass/libsass/releases/tag/3.4.9).

**Comment by mouhannad-sh** [comment]
@rodneyrehm 
libsass 3.5 is on the stable branch

https://github.com/sass/libsass/tree/3.5-stable

is there any hope to upgrade to the latest stable release ? I think it will work wonders with support to css custom variables var(--variable)

**Comment by rodneyrehm** [comment]
right, I totally forgot about this, sorry. Thanks for pinging me. I'll try to work on this next week.

**Comment by ritwickdey** [comment]
I'm trying to upgrade it from my laptop (linux), I don't know why it is producing 300KB file whereas it should be almost 3MB (sass.sync.js & sass.worker.js)

**Comment by ritwickdey** [comment]
emscripten 1.38.6 

Which version you're using?

-----

`emcc -v`

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.6
clang version 6.0.1  (emscripten 1.38.6 : 1.38.6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ritwick/Desktop/emsdkInstallation/emsdk/clang/e1.38.6_64bit
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by rodneyrehm** [comment]
release [0.10.10](https://github.com/medialize/sass.js/releases/tag/0.10.10) upgrades libsass to 3.5.4 - sorry for the daly
