### ISSUE TITLE
File to read not found or unreadable: /sass/../../test.scss

### ISSUE THREAD

**Issue by Simpleqode** [medialize/sass.js#93]
I am working on Windows. Here is where my plugin files are:

`app/assets/plugins/sassjs/`;

I am doing some test in my index.html file which is located at:

`app/index.html`

I add the following code to compile test.scss:

```
sass.compileFile('../../test.scss', function(result) {
    console.log( result );
});
```
test.scss is located at `app/assets/test.scss`. I have actually tried to place it in every folder at every level and I still get this error. What am I doing wrong?

Update: I check the Sources tab in the console and the files is loaded alrigh according to it. File permissionas are also OK.

**Comment by rodneyrehm** [comment]
can you share the code that imports the `test.scss`?

Note that `compileFile()` does not use URLs relative to your document, so `../../test.scss` should not find anything, try:

```js
sass.writeFile('app/assets/test.scss', '/* your SCSS */')
sass.compileFile('app/assets/test.scss', function(result) {
    console.log( result );
});
```

**Comment by Simpleqode** [comment]
Thanks for the answer. I actually rewrote the code to make it look like you answered in this thread: https://github.com/medialize/sass.js/issues/45, e.g. via preloadFiles and then compileFiles in the callback function and it did the trick, so I guess the issue can be closed.

PS: I tried the code you suggested in this thread with writeFile and it actually compiles only this part: /* your SCSS */ ignoring the contents of test.scss (even though it seems to be loaded). Not sure what I am doing wrong, but since the preloadFiles version works OK, I am OK with it too. Thanks again.

**Comment by rodneyrehm** [comment]
> … compiles only this part: /* your SCSS */ ignoring the contents of test.scss

you can have a file loaded (as in the DevTools' network tab shows the resource), but not registered with Sass.js (via calling `sass.writeFile(filename, content)`). Sass.js only works with the data you provide it, see [Working with files](https://github.com/medialize/sass.js/blob/master/docs/api.md#working-with-files) for more details
