### ISSUE TITLE
Save file and project.

### ISSUE THREAD

**Issue by iLenTheme** [medialize/sass.js#98]
Hello, I think it's the best sass player but I would like you to add the option to save each created file from the main one to the others created, as well as you can save all the files with the possibility of importing them again to continue playing.
Currently if the next day I want to start playing I do not have the files of the previous day, it does not give me the option to save them or import them. **Could you add this feature?**

**Comment by rodneyrehm** [comment]
Hey There!
I'm not sure I fully understand your problem. Are you using sass.js in the browser or in node (or similar)? What exactly do you mean by saving and importing importing files? Do you want to write the compilation result to your computer's file system or one of the browser's storage systems (LocalStorage, IndexedDB, …)? How would importing the previous day's result behave in your app/website? Why do you think this should be handled by sass.js?

**Comment by iLenTheme** [comment]
I think he expresses me wrong.

1) I like your page https://sass.js.org/ to practice sass
2) Could you add the functionality of saving the files created on your page to have them saved on my PC ?, that is; You can download all the files or the entire project created online.
3) If point 2 is possible, then you could add import and export files on your page to continue playing or practicing with previous created files?

I hope this time to have been clear.

**Comment by rodneyrehm** [comment]
I see. I believe you might be better served using one of these (all of them featuring options to save stuff to their servers):

* http://jsbin.com/
* https://jsfiddle.net/
* https://codepen.io/

Good luck! :)
